### ISSUE TITLE
I need help setting it up

### ISSUE THREAD

**Issue by nanospearing** [1UC1F3R616/Google-Forms-Spam#11]
I have no idea how to get this to work, and getting proxies. Here’s the form I am trying to spam: https://docs.google.com/forms/d/e/1FAIpQLSeyWh-VRTCb64kB0hekXSx3xAt-D2ZE5rG8YQWwJClK0PFezw/viewform

**Comment by searchformyusername** [comment]
- see the video plz

**Comment by searchformyusername** [comment]
- also letting u know that yes this form can be spammed as there's no signin check
