### ISSUE TITLE
about this hack

### ISSUE THREAD

**Issue by krishna830** [1UC1F3R616/Google-Forms-Spam#2]
hii sir i am krishna who contacted u on mail . can u plz help in working of this hack its not working by our side .

**Comment by 1UC1F3R616** [comment]
Please give some brief on what is not working for you.

You have to change only 4 values, You can proceed doing that by firstly opening the google form you have to be spamming
- Open your network tab of browser and watch for api calls
- Fill the form (dummy) and click send
- Find which api was used and from there take those values from headers and request that you have to be adding in the script
- Add some fresh proxies | you can google or use fastProxy
- Now run the script
- Happy Spam

Note:
- If form is gmail protected then there is no way to spam that
- You get form url when u submit it, some background is needed to fill the values

**Comment by bryanseah234** [comment]
what do u mean gmail protected?

**Comment by 1UC1F3R616** [comment]
You have to be logged in submit a response to the form and so it won’t
accept more than one form submission from a single account
