### ISSUE TITLE
Can you please tell me and give me a code which can inject random data every time when I run the program?

### ISSUE THREAD

**Issue by darshjaiswal** [1UC1F3R616/Google-Forms-Spam#3]
Can you please tell me and give me a code which can inject random data every time when I run the program?

**Comment by 1UC1F3R616** [comment]
@darshjaiswal I use faker for that purpose, [here](https://pypi.org/project/Faker/)

**Comment by darshjaiswal** [comment]
> @darshjaiswal I use faker for that purpose, [here](https://pypi.org/project/Faker/)

Bro how to can I fit Faker in your code, can you give a example code?  It works perfectly and I also used the proxy module made by you it was awesome

**Comment by 1UC1F3R616** [comment]
@darshjaiswal I use tor proxy, it is best to use will add code snippet for how to.
For how to add faker in this script, simply
- import faker
- read the documentation to find what fields you need
- when you are sending those name etc at there replace them with the variables and in those variables pass this faker content

See their in data, in that fill some values and then see where they are, Replace them accordingly
