### ISSUE TITLE
need some help.

### ISSUE THREAD

**Issue by kolt0912** [1UC1F3R616/Google-Forms-Spam#5]
Hello so 
https://docs.google.com/forms/d/e/1FAIpQLScKMRohMkPU0_GcyW0YbNQR8VFEWGISleQrhVcGnD7R84VxWg/viewform
is the form. I cant figure out where to put it..  I just need the 1st answer box to have specifically Glisten capital G case sensitive. in it. i was hoping to do atleast 5000 submissions but I need your help.

**Comment by 1UC1F3R616** [comment]
@kolt0912 fill this form first, then You have to replace those 4 values.
This is url to the form, it's not used directly.

**Comment by 1UC1F3R616** [comment]
https://drive.google.com/file/d/179iQSYu4lPIUbl85ba_bGpAXcMT79BYA/view
